### ISSUE TITLE
Sans => Dufour Sans

### ISSUE THREAD

**Issue by edufoursans** [fentec-project/gofe#21]
Hi everyone,

I'm one of the authors of the quadratic FE and the IP DMCFE papers you implement; glad to see they have attracted interest. My family name is actually Dufour Sans, not Sans, but most academic software has a hard time figuring it out. Could you please correct the citations and the acronyms? That'd be very much appreciated.

Cheers,
Edouard

**Comment by janhartman** [comment]
Hey, I corrected the citations. Hope this is OK.

**Comment by edufoursans** [comment]
Hi,

Thanks for your help. The citations are correct but the acronym "SGP" is not consistent now, it should be "DGP".

Best,
Edouard

**Comment by miha-stopar** [comment]
Hi Edouard,

it is just the name of the struct. All over documentation (project deliverables) and papers that have been accepted (and the final versions have just been submitted) we use SGP - we are not going to change this now. Maybe in the future.

Cheers

**Comment by edufoursans** [comment]
Hi Miha,

Thanks for your response and sorry my late reaction.

If this is about preserving Backward Compatibility would you accept a pull request that fixes it but also defines aliases with SGP, eg: https://github.com/edufoursans/gofe/commit/1e7a5a0f5ad2524b005ce8a5783b41614d5c86cb

It doesn't seem to break fentec-project/neural-network-on-encrypted-data

Cheers,
