### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by bquast** [fentec-project/gofe#30]
Hi,

I'm very familiar with go, but I had in to install the following dependencies to avoid errors:

bn256
pkg/errors
stretchr/testify/assert

**Comment by tilenmarc** [comment]
Hi!
Thanks for your comment. We will update the `README.md` in section `Building GoFE` to say:
"First, download and build the library by running `go get -u -t github.com/fentec-project/gofe/...` from the terminal."
Note that I added `/...` to the end of the command, which should (as far as I know) recursively install all the dependencies.
Kind regards,
Tilen

**Comment by bquast** [comment]
Thanks, and that should've read that: I'm *not* very familiar with go (which must've been obvious)
