### ISSUE TITLE
[FAME] Support for string instead of int in key attributes

### ISSUE THREAD

**Issue by remiphilippe** [fentec-project/gofe#35]
The key attributes are ints today (gamma - https://github.com/fentec-project/gofe/blob/master/abe/fame.go#L231). This is a bit of a compatibility problem with existing data formats in software and is pretty restrictive :) 

In my scenario, I want to pass UUID (a user can access multiple projects, each project already has a UUID, converting a 128 bit UUID to a 64-bit int would risk collision). It would seem useful to support a more generic data type such as a string (interface{} would force quite some work on reflection).

I've modified the code in my branch (which works all tests passes), but there are a few caveats.
- I'm no cryptography guru :)
- I moved each encryption in a separate package, make it easier to figure out boundaries (IMHO).
- GPSW and FAME share the same policy implementation, I haven't really looked at GPSW but seems to be there are some more int related checks (for example https://github.com/fentec-project/gofe/blob/master/abe/gpsw.go#L182)
- To solve the shared policy dependency, I added embedded structs (https://github.com/remiphilippe/gofe/blob/attrib-key-string/abe/fame/msp.go#L6 reduces the code changes)
- To keep GPSW working, I added a new `RowToAttribI` (https://github.com/remiphilippe/gofe/blob/attrib-key-string/abe/policy.go#L38), added a format parameter (int or string, should really be a const but it was a test https://github.com/remiphilippe/gofe/blob/attrib-key-string/abe/policy.go#L53) and redefined the `BooleanToMSP` per package (https://github.com/remiphilippe/gofe/blob/attrib-key-string/abe/gpsw/msp.go#L20 and https://github.com/remiphilippe/gofe/blob/attrib-key-string/abe/fame/msp.go#L20)

All this means introducing a breaking change due to the package change.

I have the working changes here: https://github.com/remiphilippe/gofe/tree/attrib-key-string/abe let me know what you think and if that's something we could look at merging (in some shape or form)?

**Comment by tilenmarc** [comment]
Hi remiphilippe!
Thanks for your suggestion and sorry for a late reply - I wanted to consult a colleague before deciding.
We like your idea, and we will look into how do to this change in a smart way. In particular, some limitations need to be introduced to strings as key attributes. Will have to look also how this change affects GPSW scheme.
Will let you know in the next week!

**Comment by tilenmarc** [comment]
Hi remiphilippe!
I took some code of yours and made changes so that FAME takes attributes as strings (without (,),AND, and OR).
Instead of changing to separate packages, I rather changed GPSW. It now can handle ints and strings of ints (in the case of GPSW it still must be ints since the scheme kind of demands it).
If you can, maybe check the pull request, or test it if it is ok:
https://github.com/fentec-project/gofe/pull/36
Best, Tilen

**Comment by tilenmarc** [comment]
This change is not integrated so I am closing the issue.
