### ISSUE TITLE
How to convert key to short code

### ISSUE THREAD

**Issue by ystyle** [fentec-project/gofe#39]
like this

![1F3B84C82C7D30F0387DE8291391E85A](https://user-images.githubusercontent.com/4478635/90396305-9371a100-e0c8-11ea-9843-315126b1e6c4.jpg)
I saw on this website: https://asecuritysite.com/encryption/go_abe

**Comment by tilenmarc** [comment]
Hi! Sorry for the late response, it's summer/vacations time.
You will need to write some code to translate a key into a string. One method to do so is to use [`gob` package](https://golang.org/pkg/encoding/gob/). This will allow you to change a go struct into a string, see an example on the website. In the case of GoFE, for example in ABE FAME scheme, the key is a struct and you can change it into a string.
Let me know if you managed or have some further questions.
Best, Tilen

**Comment by ystyle** [comment]
It works(use gob), but I can’t find a way to compress it so short
