### ISSUE TITLE
How to calculate intermediate values in multi input scheme?

### ISSUE THREAD

**Issue by b-rohit** [fentec-project/gofe#41]
I followed the [example](https://github.com/fentec-project/gofe/blob/master/README.md#using-a-multi-input-scheme) given in the README file. I understood the [Decrypt](https://github.com/fentec-project/gofe/blob/2ce1030d0723d8fd1abe9c86b817a034039a088f/innerprod/simple/ddh_multi.go#L217) function returns the mod after executing decryption for number of Slots times. I am interested in how can I calculate intermediate values (c, OTPKey) defined in the Decrypt function. I put some debug logs in the function and checked the [research paper ](https://eprint.iacr.org/2017/972.pdf)but could not come up with formula. 
Use following sample values.
```
X :  [ 3 3 4  2 3 2]
Y :  [ 1 2 1  1 0 1]
opt key:  [ 2 3 1  4 2 3]
c0:  2
c1:  1
OTPKey  1
```
Could someone explain how c0, c1 and OTPKey can be calculated ?

**Comment by tilenmarc** [comment]
Hi,
I am not sure what exactly are you asking. Do you want to know how `c` and `OTP` are calculated? OTP is just a random vector that gets created by the central authority during master keys generation (function `GenerateMasterKeys`) and OTPkey is then derived out of it for the decryption. Not sure what you mean by c0 and c1, please explain a bit more precise.
Best, Tilen

**Comment by b-rohit** [comment]
Yes, I want to know how c is calculated not in terms of encryption and decryption but in simple maths operations.

**Comment by tilenmarc** [comment]
I am guessing that by `c` you mean the variable defined in the implementation of the decryption. The algorithm is an implementation of algorithm in Figure 3 in [this paper](https://eprint.iacr.org/2017/972.pdf). In the paper these values are named `D_i`. They are the decryptions using the underlying DDH based scheme. If you want to see the exact math operations used to get them check the algorithm used in the decryption of DDH based scheme in [this paper](https://eprint.iacr.org/2015/017.pdf). You can also directly check the code [here](https://github.com/fentec-project/gofe/blob/b7daa712e47b4520b644d71c8ccd1e60eddfac5c/innerprod/simple/ddh.go#L221)
