### ISSUE TITLE
Key serialization 

### ISSUE THREAD

**Issue by jiep** [fentec-project/gofe#45]
Thanks for this awesome library!

Is it possible to serialize keys to a file? I didn't find any info about serialization.

Thanks in advance!

**Comment by jiep** [comment]
I finally was be able to serialize and deserialize by using the `gob` encoding.

Reference code:
* Read: https://riptutorial.com/go/example/27480/how-to-read-data-from-file-and-decode-with-go-
* Write: https://riptutorial.com/go/example/27479/how-to-encode-data-and-write-to-file-with-gob-

**Comment by tilenmarc** [comment]
Hey,
yes you are right, serialization is probably easiest if you use `gob` package. There probably exist other more efficient (in terms of the size of the saved file) alternatives, but I haven't tested any.
