### ISSUE TITLE
Could we implement the paillier-based DMCFE? 

### ISSUE THREAD

**Issue by xfap** [fentec-project/gofe#46]
cause, I find it hard to implement the KeyGen algorithm for paillier-based DMCFE described in ACK+19(Abdalla, Benhamouda, Kohlweiss, Waldner). 

To implement it, we have to find a way to generate n random vectors v_i such that the sum of v_i is 0. And the v_i should be in Z_n^M. I suppose that we could use the DH key exchange just like in DDH-based DMCFE, and then hash Z_q^M to the Z_n^M, which may not be secure; otherwise, I don't know how to resolve it.

So, my question is: could we do it？ And if you think about implementing the paillier-based DMCFE?

**Comment by tilenmarc** [comment]
Hi,
yes it is perfectly secure if you implement it just like in DDH-based DMCFE, you then theoretically base the security on DDH assumption and DCR assumption. I am not aware of any DCR based (non-iteractive) key-exchange.
If you implement it, we will gladly review and accept a pull request. For now we are a bit busy with some other project, maybe sometime in the future we will also implement this.

**Comment by xfap** [comment]
thanks
